#! /bin/bash
# 

unset $var
while $var; do
	echo 'Please enter directory of omega.dat files'
	read -e folder
	var=false
done
# folder=~/dev/nms/examples

ls -1 $folder/*omega*.dat > plotlist
end=`cat plotlist |wc -l`


for (( i=1; i<=end; i++)) do
	ifile=`cat plotlist | awk 'NR=='$i'{print($1)}'`
	ofile=`echo $ifile | cut -d '.' -f1`
	echo $ifile
	echo $ofile
	# select page orentation: ('-P' for portrait; '' for landscape)
	set orientation = '-P'
	#
	# call this variable in all (PS-producing) commands that you add
	# (remove -V if you do not want verbose mode)
	o='-K -V -O'

	R='-R0.36/1.0/200/450'
	J='-JX5.0/5.0'

	########
	#write PS header and time stamp
	echo 0 0  | psxy -R1/2/1/2 -JX10/10 -Sp -K > $ofile.ps
	#
	#
	psxy $ifile $R $J $o -Bf0.05a0.1:"frequency (mHz)":/f5a50:"Q"::."Normal mode frequencies for @-O@-S@-3@-, @-O@-T@-4@-, @-O@-S@-4@-, @-O@-T@-5@-":WSne -Sd0.07 -W1 -G0 -Y7 >> $ofile.ps
	#
	#
	# write PS trailer 
	echo 0 0  | psxy -R1/2/1/2 -JX10/10 -Sp -O >> $ofile.ps
	#
	convert -density 300 $ofile.ps $ofile.pdf
	# lpr -Plw $ofile.pdf
	
	#okular $ofile &
done
rm plotlist